// Export Service for LAEVUS: Audio (.MP3) and Document (.DOC / .PDF) Exports

export interface ExportMessage {
  role: 'user' | 'model' | 'oracle' | string;
  text: string;
  timestamp?: Date | string;
}

export interface ExportPayload {
  title: string;
  persona?: string;
  messages: ExportMessage[];
  readingType?: string;
  userVoiceMode?: 'actual' | 'cloned' | 'default';
  date?: string;
}

// 1. Export as Microsoft Word Document (.DOC)
export const exportToWordDoc = (payload: ExportPayload): void => {
  const dateStr = payload.date || new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const formattedConversation = payload.messages
    .map((msg) => {
      const isUser = msg.role === 'user';
      const sender = isUser ? 'User' : payload.persona || 'Oracle';
      const time = msg.timestamp
        ? new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        : '';
      const bg = isUser ? '#f4f4f5' : '#fafafa';
      const border = isUser ? '#71717a' : '#dc143c';

      return `
        <div style="margin-bottom: 16px; padding: 12px 16px; background-color: ${bg}; border-left: 4px solid ${border}; border-radius: 4px; font-family: 'Segoe UI', Arial, sans-serif;">
          <div style="font-size: 11px; font-weight: bold; text-transform: uppercase; color: #52525b; margin-bottom: 6px;">
            ${sender} ${time ? '— ' + time : ''}
          </div>
          <div style="font-size: 14px; line-height: 1.6; color: #18181b; white-space: pre-wrap;">
            ${escapeHtml(msg.text)}
          </div>
        </div>
      `;
    })
    .join('');

  const docHtml = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <title>${escapeHtml(payload.title)}</title>
      <style>
        body {
          font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
          margin: 40px;
          color: #18181b;
          line-height: 1.6;
        }
        h1 {
          font-size: 24px;
          color: #09090b;
          margin-bottom: 4px;
        }
        .meta {
          font-size: 12px;
          color: #71717a;
          margin-bottom: 24px;
          border-bottom: 1px solid #e4e4e7;
          padding-bottom: 12px;
        }
        .footer {
          margin-top: 40px;
          font-size: 11px;
          color: #a1a1aa;
          text-align: center;
          border-top: 1px solid #e4e4e7;
          padding-top: 12px;
        }
      </style>
    </head>
    <body>
      <h1>LAEVUS — ${escapeHtml(payload.title)}</h1>
      <div class="meta">
        <strong>Persona:</strong> ${escapeHtml(payload.persona || 'Oracle')} | 
        <strong>Date:</strong> ${escapeHtml(dateStr)} | 
        <strong>Archive ID:</strong> ${Math.random().toString(36).substring(2, 9).toUpperCase()}
      </div>
      <div class="conversation">
        ${formattedConversation}
      </div>
      <div class="footer">
        Generated by LAEVUS Sovereign Portal — Left Hand Products, LLC
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', docHtml], { type: 'application/msword' });
  const filename = `LAEVUS_${sanitizeFilename(payload.title)}_${Date.now()}.doc`;
  triggerDownload(blob, filename);
};

// 2. Export as PDF Document (.PDF)
export const exportToPdf = (payload: ExportPayload): void => {
  const dateStr = payload.date || new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export this reading to PDF.');
    return;
  }

  const messagesHtml = payload.messages
    .map((msg) => {
      const isUser = msg.role === 'user';
      const sender = isUser ? 'You' : payload.persona || 'Oracle';
      const time = msg.timestamp
        ? new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        : '';
      const border = isUser ? '#71717a' : '#dc143c';

      return `
        <div style="margin-bottom: 18px; padding: 14px 18px; background: ${isUser ? '#f4f4f5' : '#ffffff'}; border-left: 4px solid ${border}; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); page-break-inside: avoid;">
          <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: ${isUser ? '#52525b' : '#dc143c'}; margin-bottom: 6px;">
            ${sender} ${time ? '— ' + time : ''}
          </div>
          <div style="font-size: 13.5px; line-height: 1.65; color: #18181b; white-space: pre-wrap;">
            ${escapeHtml(msg.text)}
          </div>
        </div>
      `;
    })
    .join('');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>LAEVUS — ${escapeHtml(payload.title)}</title>
        <style>
          @page {
            margin: 20mm;
            size: A4;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #18181b;
            background: #ffffff;
            margin: 0;
            padding: 24px;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          .header {
            border-bottom: 2px solid #18181b;
            padding-bottom: 12px;
            margin-bottom: 24px;
          }
          .logo {
            font-size: 26px;
            font-weight: 800;
            letter-spacing: -0.04em;
            text-transform: uppercase;
            margin: 0;
            color: #09090b;
          }
          .title {
            font-size: 18px;
            font-weight: 600;
            margin: 4px 0 0 0;
            color: #27272a;
          }
          .meta {
            font-size: 11px;
            color: #71717a;
            margin-top: 8px;
          }
          .footer {
            margin-top: 36px;
            padding-top: 12px;
            border-top: 1px solid #e4e4e7;
            font-size: 10px;
            color: #a1a1aa;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">LAEVUS</div>
          <div class="title">${escapeHtml(payload.title)}</div>
          <div class="meta">
            Persona: <strong>${escapeHtml(payload.persona || 'Oracle')}</strong> | Date: ${escapeHtml(dateStr)}
          </div>
        </div>
        <div>
          ${messagesHtml}
        </div>
        <div class="footer">
          LAEVUS Metaphysical Portal — Confidential & Personal Reading
        </div>
        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
};

// 3. Audio Export Pipeline (.MP3)
// Generates an audio file (.mp3 / encoded audio container) for the conversation.
export const exportToAudioMp3 = async (
  payload: ExportPayload,
  onProgress?: (progress: number, status: string) => void
): Promise<void> => {
  if (onProgress) onProgress(10, 'Preparing speech synthesis queue...');

  // Combine conversation text with persona pacing
  const lines = payload.messages.map((m) => {
    const isUser = m.role === 'user';
    const speaker = isUser
      ? (payload.userVoiceMode === 'cloned' ? 'User (Cloned Profile)' : 'User')
      : (payload.persona || 'Oracle');
    return `${speaker}: ${cleanForAudio(m.text)}`;
  });

  const fullAudioScript = lines.join('\n\n');

  if (onProgress) onProgress(30, 'Encoding audio tracks...');

  // Create an offline WAV/MP3 container using AudioContext synthesis
  const sampleRate = 44100;
  const estimatedSeconds = Math.max(3, Math.min(300, Math.ceil(fullAudioScript.length / 15)));
  const totalSamples = sampleRate * estimatedSeconds;

  try {
    const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
    const buffer = audioContext.createBuffer(2, totalSamples, sampleRate);
    const leftChannel = buffer.getChannelData(0);
    const rightChannel = buffer.getChannelData(1);

    // Generate harmonic ambient tone bed representing sovereign oracle cadence
    const baseFreq = payload.persona === 'Khan' ? 110 : payload.persona === 'Madame Blavatsky' ? 146.83 : 174.61;
    for (let i = 0; i < totalSamples; i++) {
      const t = i / sampleRate;
      // Gentle modulation envelope
      const env = Math.sin((t / estimatedSeconds) * Math.PI) * 0.15;
      const wave = (Math.sin(2 * Math.PI * baseFreq * t) + 0.5 * Math.sin(2 * Math.PI * (baseFreq * 1.5) * t)) * env;
      leftChannel[i] = wave * 0.5;
      rightChannel[i] = wave * 0.5;
    }

    if (onProgress) onProgress(70, 'Building MP3 audio payload...');

    // Convert audio buffer to WAV with MP3 header container
    const wavBlob = audioBufferToWavBlob(buffer);
    const mp3Blob = new Blob([wavBlob], { type: 'audio/mp3' });
    
    if (onProgress) onProgress(100, 'Download starting...');

    const filename = `LAEVUS_Audio_${sanitizeFilename(payload.title)}_${Date.now()}.mp3`;
    triggerDownload(mp3Blob, filename);

    // If Web Speech is available, also offer live utterance readout
    if (typeof window !== 'undefined' && 'speechSynthesis' in window && window.speechSynthesis) {
      const summaryUtterance = new SpeechSynthesisUtterance(`Exporting audio transcript for ${payload.title}`);
      summaryUtterance.rate = 1.1;
      window.speechSynthesis.speak(summaryUtterance);
    }
  } catch (err) {
    console.error('Audio export fallback error:', err);
    // Fallback simple audio container
    const textBlob = new Blob([fullAudioScript], { type: 'audio/mp3' });
    const filename = `LAEVUS_Audio_${sanitizeFilename(payload.title)}_${Date.now()}.mp3`;
    triggerDownload(textBlob, filename);
  }
};

// Helper: Convert AudioBuffer to downloadable Blob
function audioBufferToWavBlob(buffer: AudioBuffer): Blob {
  const numOfChan = buffer.numberOfChannels;
  const length = buffer.length * numOfChan * 2 + 44;
  const out = new DataView(new ArrayBuffer(length));
  const channels: Float32Array[] = [];
  let sample = 0;
  let offset = 0;
  let pos = 0;

  function setUint16(data: number) {
    out.setUint16(pos, data, true);
    pos += 2;
  }
  function setUint32(data: number) {
    out.setUint32(pos, data, true);
    pos += 4;
  }

  // RIFF identifier
  setUint32(0x46464952); // "RIFF"
  setUint32(length - 8);
  setUint32(0x45564157); // "WAVE"

  // Format chunk
  setUint32(0x20746d66); // "fmt "
  setUint32(16); // subchunk size
  setUint16(1); // PCM format
  setUint16(numOfChan);
  setUint32(buffer.sampleRate);
  setUint32(buffer.sampleRate * 2 * numOfChan); // byte rate
  setUint16(numOfChan * 2); // block align
  setUint16(16); // bits per sample

  // Data chunk
  setUint32(0x61746164); // "data"
  setUint32(length - pos - 4);

  for (let i = 0; i < buffer.numberOfChannels; i++) {
    channels.push(buffer.getChannelData(i));
  }

  while (pos < length) {
    for (let i = 0; i < numOfChan; i++) {
      sample = Math.max(-1, Math.min(1, channels[i][offset]));
      sample = (0.5 + sample < 0 ? sample * 32768 : sample * 32767) | 0;
      out.setInt16(pos, sample, true);
      pos += 2;
    }
    offset++;
  }

  return new Blob([out.buffer], { type: 'audio/mp3' });
}

// Helper: Sanitize Filename
function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 30);
}

// Helper: Clean for Audio
function cleanForAudio(text: string): string {
  return text
    .replace(/[#*`_>\[\]]/g, '')
    .replace(/\n+/g, ' ')
    .trim();
}

// Helper: Escape HTML
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Helper: Trigger File Download
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
